title: Nico Braun
socials:
  - title: bluebrown
    anchor: https://github.com/bluebrown
    icon: github
  - title: codingsafari
    anchor: https://www.twitter.com/codingsafari
    icon: twitter
  - title: nico-braun
    anchor: https://www.linkedin.com/in/nico-braun
    icon: linkedin
  - title: the-fool
    anchor: https://stackoverflow.com/users/9208887/the-fool
    icon: stackoverflow
